### ISSUE TITLE
Loss Recovery and Congestion Control Pseudocode for multipath

### ISSUE THREAD

**Issue by Yanmei-Liu** [quicwg/multipath#111]
Do we need some pseudocode like [RFC 9002 Appendix-A](https://datatracker.ietf.org/doc/html/rfc9002#appendix-A) and [Appendix-B](https://datatracker.ietf.org/doc/html/rfc9002#appendix-B) to describe the loss recovery and congestion control processes which are different in multiple paths?  Besides, some of the functions are different in multiple and single packet number space. 
This might be helpful when people try to understand and implement the mechanisms.

**Comment by qdeconinck** [comment]
Depending on how the discussions evolve about the packet number space designs, if we end up having some single packet number space at some point, it would be interesting to show the adapted loss recovery algorithm. In particular, in DetectAndRemoveLostPackets, the packet threshold must be relative to the packet sent over a path (and not be based on the absolute connection-wide number, as any multipath reordering would cause spurious retransmissions).

However, I'm not sure to understand why we should provide alternative algorithms for congestion control. To me, we can just state that these are applied per-path and not connection-wide and this should be sufficient.

**Comment by obonaventure** [comment]
If we want to provide a Reno like pseudocode, it should be a coupled congestion control scheme that shows how different paths would be coupled. Not sure that someone would deploy such as congestion control...

**Comment by huitema** [comment]
At this point in the document progress, the question with most issues should be, "can we leave it out". For this one, I think we certainly can. RFC are protocol specs, not implementation tutorials. If the spec is clear, leave it at that.

**Comment by qdeconinck** [comment]
I think the current content of Section 7.2 (Implementation Considerations: Congestion Control) is sufficient. If at some point we would want to provide pseudocode for such algorithms, they would better be located in companion drafts (that would describe such algorithms), but not this base one.

**Comment by mirjak** [comment]
Can we close this issue?
