### ISSUE TITLE
Path idle timeout for Path State Figure in Section 4.2

### ISSUE THREAD

**Issue by yfmascgy** [quicwg/multipath#115]
For the transition from a "closing" state to a "closed" state In the path state figure in section 4.2, I find the phrase "path idle timeout" a bit confusing, because right now this value is supposed to be equal to max_idle_timeout, but shouldn't a transition from a "closing" state to a "closed" state be much quicker than that from an "active" state to a "closed" state since the first transition is just what we expect to happen?

**Comment by qdeconinck** [comment]
I think this is now fixed by #116.
