### ISSUE TITLE
Handle stateless reset

### ISSUE THREAD

**Issue by huitema** [quicwg/multipath#118]
Should the spec say something about stateless reset?

Suppose a node is sending on two paths with two different DCID and two corresponding stateless reset secrets, and receives a stateless reset packet that matches the reset secret on the first path. Should it:

1) Abandon that path and continue the connection with the other path?
2) Abandon the connection?

**Comment by qdeconinck** [comment]
That's a good point. RFC9000 states that stateless resets should be used in last resort when the endpoint does not have access to the connection state. If hosts have still access to the connection state and want to abandon a specific path, I would expect them to rely on PATH_ABANDON frame (or on path idle timeout). So I would abandon the connection.

Depending on the number of impacts on existing RFC9000 mechanisms, it may be useful to write a section (or at least, a paragraph) clarifying these points.
