### ISSUE TITLE
Handling incoming ACK_MP frames with a retired DCID sequence number

### ISSUE THREAD

**Issue by qdeconinck** [quicwg/multipath#122]
It might be possible to be in a state where a sender retires a DCID that was used by still in-flight packets. Hence, it is possible for the sender to receive a ACK_MP frame referencing the retired DCID. Depending on the situation:

- The sender can keep a way to track the sent packet with the retired DCID sequence number, allowing proper acknowledgement of the packets.
- The sender drops all the state related to the DCID, hence marking the in-flight packets as being lost and ignoring ACK_MP frames having a retired DCID sequence number.

While this should not affect interoperability, it might be worthwhile to add a sentence or two to mention the possible performance issue in such situation.

**Comment by mirjak** [comment]
We could add some text to [4.2.2. ](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#section-4.2.2)[Effect of RETIRE_CONNECTION_ID Frame](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#name-effect-of-retire_connection). Can you propose a PR @qdeconinck ?
