### ISSUE TITLE
Guidance on scheduling of packets containing ACK frames

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#123]
This issue came up during the discussion of issue #33. We say that ACK or ACK_MP frames can be send over any path, however, maybe we should discuss some guidance and trade-offs. E.g. sending on the same path as the packets received also for RTT measurements; using the shortest delay path might have some performance benefits...?

**Comment by yfmascgy** [comment]
I agree. We should add some guidance here. We did some experiment regarding this issue. Our finding is returning ACK on the shortest path is helpful. But the improvement is only more significant when the path rtt ratio is larger than 4:1.
