### ISSUE TITLE
Add more explanation on ACK delay and zero-length CID

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#125]
Comment by @yfmascgy (on PR #103):
I think we expand this section a bit as we found getting the delay right was non-trivial. QUIC time-stamp would work for sure. But if one decides not to use QUIC timestamp, we probably want to explain what is needed to be done here.

**Comment by yfmascgy** [comment]
I have submitted PR #131 for this one.

**Comment by qdeconinck** [comment]
Closing as #125 got merged.
