### ISSUE TITLE
Can we be more specific about RTT computation? The word "statistical" is a bit broad.

### ISSUE THREAD

**Issue by yfmascgy** [quicwg/multipath#132]
The current draft says "If timestamps are not available, implementations could estimate one way delays using statistical techniques". I find the word "statistical" a bit too broad. Can we elaborate what is the exact statistical method recommended to use? Moreover, "statistical" also implies variation and randomness, what happens for applications that do not expect such randomness?

**Comment by huitema** [comment]
I could elaborate, but I am afraid that this is going into lots of details very quickly.


Each RTT measurement of the tuple (send path, return path) provides an evaluation of (one-way-delay(send_path, send_time) + one_way_delay(return_path, return_time)). At that point, we have to infer what is the most likely value of the one way delays that produced this result.

Whatever the number of paths and number of measurements, the system ends up with fewer equations than variables. For example, even in the single path scenario, a delay of 60 ms can be explained equally well by a delay of 30 ms in each direction, a delay of 40 ms on the send path and 20 ms or the return path, or any combination of delays that sums to 60ms. We can extract bounds, such as "the delay on segment X is not negative", but that leaves out a wide range of estimations. This is generally handled by making simple assumptions, such as assuming delays on a given path are symmetric -- until we learn something more.

Even with that symmetry hypothesis, we have to make hypotheses about the probability function for each path. Solutions like Kalman filter assume a Gaussian distribution of delays, which simplifies computations. The classic computation of smoothed RTT and RTT average in the TCP code implicitly assumes a Gaussian distribution of delays, and further simplifies the computations so they can be performed in real time. For a simple implementation, using the same kind of simplifications as seen in TCP, we can use the following algorithm:

1) Maintain estimates of average delay and delay variation for each segment.
2) When a measurement is received and delay and variation are already initialized for both segments, allocate a sample based on previous knowledge:
         * delta = rtt_sample - average(send_segment) - average(return_segment)
         * range = variation(send_segment) + variation(return_segment)
         * sample(send_segment) = average(send_segment) + delta* variation(send_segment)/range
         * sample(return_segment) = average(return_segment) + delta* variation(return_segment)/range
then update average and variation for each segment using the same formulas used for TCP.

3) When delay and variation are not estimated for either segment, split the difference:
        * sample(send_segment) = rtt_sample /2
        * sample(return_segment) = rtt_sample /2.
then initialize average and deviation for each segment based on the sample for that segment.

4) When delay and variation are only estimated for return segment, initialize the send segment:
        * sample(return_segment) = min(average(return_segment), rtt_sample)
        * sample(send_segment) = rtt_sample - sample(return_segment),
then initialize average and deviation for the send segment, but do not update estimates for the receive segment.

5) When delay and variation are only estimated for send segment, initialize the return segment:
        * sample(send_segment) = min(average(send_segment), rtt_sample)
        * sample(return_segment) = rtt_sample - sample(send_segment) 
then initialize average and deviation for the receive segment, but do not update estimates for the send segment.

**Comment by huitema** [comment]
I guess the previous text could be copied in an annex.

**Comment by yfmascgy** [comment]
> I could elaborate, but I am afraid that this is going into lots of details very quickly.
> 
> Each RTT measurement of the tuple (send path, return path) provides an evaluation of (one-way-delay(send_path, send_time) + one_way_delay(return_path, return_time)). At that point, we have to infer what is the most likely value of the one way delays that produced this result.
> 
> Whatever the number of paths and number of measurements, the system ends up with fewer equations than variables. For example, even in the single path scenario, a delay of 60 ms can be explained equally well by a delay of 30 ms in each direction, a delay of 40 ms on the send path and 20 ms or the return path, or any combination of delays that sums to 60ms. We can extract bounds, such as "the delay on segment X is not negative", but that leaves out a wide range of estimations. This is generally handled by making simple assumptions, such as assuming delays on a given path are symmetric -- until we learn something more.
> 
> Even with that symmetry hypothesis, we have to make hypotheses about the probability function for each path. Solutions like Kalman filter assume a Gaussian distribution of delays, which simplifies computations. The classic computation of smoothed RTT and RTT average in the TCP code implicitly assumes a Gaussian distribution of delays, and further simplifies the computations so they can be performed in real time. For a simple implementation, using the same kind of simplifications as seen in TCP, we can use the following algorithm:
> 
> 1. Maintain estimates of average delay and delay variation for each segment.
> 2. When a measurement is received and delay and variation are already initialized for both segments, allocate a sample based on previous knowledge:
>    * delta = rtt_sample - average(send_segment) - average(return_segment)
>    * range = variation(send_segment) + variation(return_segment)
>    * sample(send_segment) = average(send_segment) + delta* variation(send_segment)/range
>    * sample(return_segment) = average(return_segment) + delta* variation(return_segment)/range
>    then update average and variation for each segment using the same formulas used for TCP.
> 3. When delay and variation are not estimated for either segment, split the difference:
>    * sample(send_segment) = rtt_sample /2
>    * sample(return_segment) = rtt_sample /2.
>    then initialize average and deviation for each segment based on the sample for that segment.
> 4. When delay and variation are only estimated for return segment, initialize the send segment:
>    * sample(return_segment) = min(average(return_segment), rtt_sample)
>    * sample(send_segment) = rtt_sample - sample(return_segment),
>    then initialize average and deviation for the send segment, but do not update estimates for the receive segment.
> 5. When delay and variation are only estimated for send segment, initialize the return segment:
>    * sample(send_segment) = min(average(send_segment), rtt_sample)
>    * sample(return_segment) = rtt_sample - sample(send_segment)
>    then initialize average and deviation for the receive segment, but do not update estimates for the send segment.

Hi Christian, thank for the explanation. However, there is still sth that is not quite clear to me. You mentioned Kalman filter. My understanding is that your state vector is the one-way-delay for each path in each direction. For example, if I have N paths, then I could write down s=[OWD_inbound_1, ...., OWD_inbound_N, OWD_outbound_1,... OWD_outbound_N]. For the process equation, we can write s_(k+1) = s_k + w_k, where w_k is the process noise/disturbance. The difficult part in the problem is that in the observation equation H is a random matrix, which means in each measurement y, y could be the combination of one way delay various two different paths. So to me,  at the first glance, the problem is a bit different from the Kalman's formulation where observation y = H*s + v, where v is the noise term and H is fixed. I think this is not that relevant, but I am really curious to learn the techniques.

**Comment by huitema** [comment]
In a Kalman filter, if you have multiple observations, you use a different matrix H for each observation. But you maintain a single evaluation vector, correlation matrix, etc. Each observation operates on a projection of the whole state. 

But then, I do not suggest that we try implementing a full Kalman filter. That would be a bit too CPU intensive. Also, the Kalman filter is trying for a min-square estimate, which works well for Gaussian variables but is only an approximation for the kind of probability distributions that we are likely to encounter. Implementing a more precise Kalman filter would be more precisely wrong...

**Comment by qdeconinck** [comment]
Revisiting this issue now, I wonder if we should just take the same approach as the scheduling guidance, i.e., say the less and delegate advanced discussions in a potential future draft.

**Comment by mirjak** [comment]
Even if we don't provide the more detailed information in the appendix, the section on "Computing Path RTT" needs an editorial pass. I agree that the term "statistical techniques" is not very clear. I guess one option is also to say rather less than more.

@huitema can you have a look and propose a PR?

**Comment by huitema** [comment]
That would be PR #217

**Comment by mirjak** [comment]
Ah, sorry. Do plan to do another pass on #217?
