### ISSUE TITLE
Multipath-specific error codes: undefined MP_CONNECTION_ERROR

### ISSUE THREAD

**Issue by qdeconinck** [quicwg/multipath#136]
In section 3, we have

```
If endpoint receives an unexpected value for the transport parameter "enable_multipath", it
MUST treat this as a connection error of type MP_CONNECTION_ERROR and close the connection.
```

However, the `MP_CONNECTION_ERROR` error code does not exist (anymore), and I'm not sure we need such a specific error code anyway. Why not raising a `TRANSPORT_PARAMETER_ERROR` in such case?

**Comment by Yanmei-Liu** [comment]
It's reasonable to use TRANSPORT_PARAMETER_ERROR.
Submitted PR #141 for this issue.
