### ISSUE TITLE
Any implementations of multipath quic?

### ISSUE THREAD

**Issue by nandsky** [quicwg/multipath#153]
Is there any multipath implementations besides xquic ("https://github.com/alibaba/xquic/tree/beta/multipath-ietf-draft-01") ?

I would appreciate for any help.

**Comment by qdeconinck** [comment]
To my knowledge, there are two other open-source implementations of Multipath QUIC: picoquic (https://github.com/private-octopus/picoquic) and "work-in-progress" Cloudflare's quiche (https://github.com/cloudflare/quiche/pull/1310). However, the specifications will again have breaking changes soon and I don't think we started interoperability tests yet (so beware for dragons).

**Comment by mirjak** [comment]
This is a question that is better suited for the mailing list. Feel free to shoot an email to quic@ietf.org ! But I will close this issue for now!
