### ISSUE TITLE
Only use either Path ID or PNS ID

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#154]
From PR #149 from @qdeconinck:

> Maybe it can be addressed later, but given that the Path Identifier and the PNS ID are now always the same, we may simplify this section and only introduce one concept (i.e., the Path Identifier).

**Comment by mirjak** [comment]
Let's do another editorial pass and evil. some re-org first and then address this issue. I think we all already agreed that we only need one of the two. So we only need to decide with name we keep.

**Comment by yfmascgy** [comment]
I prefer to use the name "Path ID", as it is more intuitive in the context of multipath.
