### ISSUE TITLE
Error code for missing CID during handshake

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#157]
Which the newly merged PR #149, the doc now says:

"If the parameter is set to 1, both endpoints MUST use non-zero connection IDs. If an enable_multipath parameter set to 1 is received and the carrying packet does not contain a non-zero length connection ID, the receiver MUST treat this as a connection error of type TRANSPORT_PARAMETER_ERROR (specified in {{Section 20.1 of QUIC-TRANSPORT}}) and close the connection."

Is it okay to use the TRANSPORT_PARAMETER_ERROR code for this or do we need a different/new one?

**Comment by yfmascgy** [comment]
I think it should be Okay. Basically, if a packet uses zero-length CID, the enable_multipath parameter should not be set to 1, and when it does, it is a TRANSPORT_PARAMETER_ERROR.

**Comment by qdeconinck** [comment]
I agree with the TRANSPORT_PARAMETER_ERROR solution (not sure it is valuable to define a new value here).

**Comment by mirjak** [comment]
Okay, I think we all agree. I'll leave the issue open until the next meeting to double-check with the group. No action needed so far.

**Comment by martinthomson** [comment]
Discussion at IETF 116 indicated a strong preference for a new error code here.
