### ISSUE TITLE
Unclear (inconsistent?) mapping of Path ID in PATH_STATUS and PATH_ABANDON frames

### ISSUE THREAD

**Issue by qdeconinck** [quicwg/multipath#164]
Since #156, we now define the Path ID as (Section 1.1)
```
the sequence number of the destination Connection ID
used for sending packets on that particular path.
```

And the definition of the `Path ID` as the field of PATH_ABANDON and PATH_STATUS frames directly maps to that identifier path (i.e., the sequence number of the destination Connection ID used for sending packets on that particular path, Sections 8.1 and 8.2).

But in Section 6.2, the example states that 
```
[the Path ID] identifies the path by the sequence number of the received packet's DCID over that path
```

I believe the current text is unclear and should be fixed. Yet, I see two possible ways of doing so. We should either state that

- the `Path ID` field of these frames refer to the Path ID used by the receiver of the frame, or
- add some information to indicate that it refers to the Path ID viewed from the sender's/receiver's viewpoint (that could be encoded as a bit in the frame's type)

**Comment by mirjak** [comment]
Is there any use case for either using the sender's or receiver's ID? If not, I'd prefer we simply choose one and define it clearly.

**Comment by mirjak** [comment]
(P.S.: I think the text in the example is just wrong. I think I messed this up in #156.)

**Comment by qdeconinck** [comment]
IMHO it makes more sense to me to use the sender's ID by default, especially if we consider only client-initiated paths.
