### ISSUE TITLE
Would it be beneficial to use the same Path ID on both sides?

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#170]
Currently the Path ID is selected based on the sequence number of the CID used to send. Alternatively we could also, add an explicit path ID in the path validation frame that is then used by both ends. This would be possible in the current spec as we assume all path to be bi-directional and only the client can open new paths, and thus could select a unique path ID. This might simplify the mental model for implementors.

**Comment by huitema** [comment]
I think this would be a major change in the desig. We do not have either a consensus or a mandate for that.
