### ISSUE TITLE
Provide more guidance on which path to use for control frames

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#183]

**Comment by qdeconinck** [comment]
We probably need to add some text in the scheduling considerations where control frames (PATH_STATUS, PATH_ABANDON, but also MAX_DATA,...) should be sent on a good working path, ideally with low latency.

**Comment by huitema** [comment]
I would say the same applies to ACK_MP

**Comment by mirjak** [comment]
For ACK we recommend (SHOULD) to send it on the same path because of RTT calculations and I believe the scheduling text discusses at already.

**Comment by huitema** [comment]
Thinking about this some more. I believe we should say *NOTHING*. The point of the standard is to specify expected behavior when a node receives protocol messages from its peer. The basic statement is that most frames, including control frames, can be sent on any path -- the only exception being PATH CHALLENGE frames and PATH_RESPONSE frames.

So my preference would be:

1) say nothing, because the purpose of standards is to specify requirements for Interop, not provide guidance to implementors.

2) if we do say something, just say that these frames can be sent on any valid path, based on preferences of the application and the implementation.

**Comment by huitema** [comment]
As for ACK_MP frames, the text says "ACK_MP frame (defined in [Section 8.3](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#ack-mp-frame)) SHOULD be sent on the same path as identified by the Path Identifier. However, an ACK_MP frame can be returned via a different path, based on different strategies of sending ACK_MP frames." That's an OK compromise, leaving open the possibility for implementations to use any strategy they want.

**Comment by LPardue** [comment]
Alternatively, spell out the considerations to make when picking a path? Does it matter, if so, why? This would be useful to know when new frames come along in the future and need to think for themselves how multipath might affect them.

**Comment by huitema** [comment]
Sure, but at this stage we have preciously little experience. For example, I have a user request to specify affinity between a stream and a path. I can certainly provide them an API to do that, but this is basically research. And then, affinity applies to stream frames, but whether it should be applied to control frames is debatable.

I am concerned that the guidance that we provide will be so generic as not to be useful, while still requiring long debates and delaying the publication of the draft. I think guidance is best provided in research papers, and possibly in text books.

**Comment by LPardue** [comment]
I agree we shoukd avoid the potential time sink.

I wasn't suggesting guidance but rather a fairly succinct statement like  "The path that frames are sent on is a local choice, which could effect the behavior or performance of the QUIC transport or delivery of application data. There is no guidance provided by this document on strategies for path selection for frames beyond the control frames for the multipath extension itself."

And perhaps gathering consensus on that now avoids people asking the question in later review rounds.

**Comment by huitema** [comment]
@LPardue I agree. Your proposal is basically equivalent to my suggestion that "if we do say something, just say that these frames can be sent on any valid path, based on preferences of the application and the implementation." Your text is good.
