### ISSUE TITLE
Does the reception of purely invalid Destination Connection ID sequence number in PATH_ABANDON/PATH_STATUS also lead to connection error?

### ISSUE THREAD

**Issue by qdeconinck** [quicwg/multipath#197]
Somewhat related to #193 (that moved text that was ACK_MP specific to all the multi path-specific frames), we currently state in the ACK_MP section that

> If an endpoint receives an ACK_MP frame with a Connection ID sequence
number which was never issued (i.e., with a sequence number
larger than the largest one advertised), it MUST treat this as a connection
error of type MP_PROTOCOL_VIOLATION and close the connection.

Should we also react the same way with PATH_ABANDON and PATH_STATUS frames? I would say yes, but would be great to agree on this.

**Comment by yfmascgy** [comment]
I think so. It should lead to connection error.

**Comment by mirjak** [comment]
At least we should react the same to all three frames. Not sure if there is a point in ignoring instead but I also think a connection error is right.
