### ISSUE TITLE
Use authors actual names

### ISSUE THREAD

**Issue by martinthomson** [quicwg/multipath#201]
Now, I might be making an assumption, but I believe that some of the authors/editors on the draft are currently using latin transliterations of their names.  We have the ability to use real names, can we do that?

(Note: we need to ask; I have had some people express a desire to only use the latin version of their name.  The most important thing is to respect individual wishes.)

**Comment by mirjak** [comment]
@Yanmei-Liu @yfmascgy how do you prefer to have you names listed? Please create a PR if you want to change or close this issue! Thanks!

**Comment by yfmascgy** [comment]
Many thanks! I think it's a good idea to also use our actual name. I was trying to input my Chinese name in Unicode as &#x9A6C;&#x4E91;&#x98DE; but when I tried make I got the following error saying that it did not find alphanumeric character "/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:456:in `parse': (<unknown>): did not find expected alphabetic or numeric character while scanning an anchor at line 25 column 10 (Psych::SyntaxError)"

**Comment by martinthomson** [comment]
The syntax is a little weird.  Try this (repeat all but the first line for other authors):

```yaml
author:
  -
    fullname:
      :: "马云飞"
      ascii: "Yanmei Liu"
    org: ...
    email: ...
```
