### ISSUE TITLE
use a FRAME_ENCODING_ERROR, not MP_PROTOCOL_VIOLATION for frame parsing errors

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/multipath#207]
RFC 9000 defines a FRAME_ENCODING_ERROR, which occurs when a frame can’t be parsed or is received at the wrong encryption level. It even contains a field to indicate the frame type.

This error would be more specific than the general MP_PROTOCOL_VIOLATION defined in this document.

**Comment by mirjak** [comment]
PR #236 replaces the error code for the case wrong encryption level case. 

The second case where MP_PROTOCOL_VIOLATION is used is when a too high CID seq num in the frame. Do we want to change that also to FRAME_ENCODING_ERROR?

**Comment by marten-seemann** [comment]
The principle we used regarding error codes in RFC 9000 is the following: If you can (statelessly) detect the error when parsing the frame, it's a FRAME_ENCODING_ERROR. If you need to access state, it's a PROTOCOL_VIOLATION (or more specific other error).

**Comment by mirjak** [comment]
As you need state about the used CID seq number, I guess this is the later case. Should we keep using MP_PROTOCOL_VIOLATION or define a more specific error type?

**Comment by marten-seemann** [comment]
No strong preference either way, but it might make sense to define an error for referencing an invalid path. Precedent for that would be the STREAM_STATE_ERROR in RFC 9000. Defining a consistent set of error codes for multipath is probably a larger design issue though that requires some more thought. Should we open a new issue for that?

**Comment by mirjak** [comment]
There is also issue #157 for the handshake error question. Not sure if we need new issue or can handle these few cases separately...
