### ISSUE TITLE
contradicting statement about usage of ACK vs ACK_MP frames

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/multipath#208]
> As soon as the negotiation of multipath support is completed, endpoints SHOULD use ACK_MP frames instead of ACK frames to acknowledge application data packets, including 0-RTT packets, using the initial Connection ID with sequence number 0 after the handshake concluded

The extension is negotiated when the EncryptedExtensions has been sent / received, which is during the handshake, so it sounds like this would allow ACK_MP frames in Handshake packets.

However:
> Acknowledgements of Initial and Handshake packets MUST be carried using ACK frames, as specified in [[QUIC-TRANSPORT](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#QUIC-TRANSPORT)].

**Comment by kazuho** [comment]
So maybe the solution would be to state that ACK_MP can be send in 1-RTT packets only, and that handshake must complete in one path?

**Comment by huitema** [comment]
I think it will have to be handshake complete, actually, because of the "preferred address" option. Otherwise there would be ambiguity as to whether the "preferred address" path is treated as one of many paths or as a replacement for the original path.

**Comment by huitema** [comment]
On the other hand, no harm is done if the server sends ACK_MP(Cid-number = 0, ...).

**Comment by kazuho** [comment]
Right, regarding @marten-seemann's original concern regarding if ACK_MP frames can be sent in Initial and Handshake packets, the Multipath draft already prohibits the use of ACK_MP frames in Initial and Handshake packets.

[Section 8](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#name-new-frames) states that _all the new frames MUST only be sent in 1-RTT packet, and MUST NOT use other encryption levels_.

Though we can always be more clear about it being prohibited.

I have opened a separate issue (#220) regarding the use of standard ACK frames in 1-RTT packets when multipath is negotiated.

**Comment by mirjak** [comment]
To come back to the original text that Martin cited. This is not a contradiction because the text says: "SHOULD use ACK_MP frames instead of ACK frames to acknowledge application data packets."


I guess the term "application data packets" is not very clear though.

As such I think this issue is just editorial to clarify this term. Or can we close this issue and just ensure we clarify issue #220?

**Comment by mirjak** [comment]
No action needed - issue #220 covers the discussion about use of RFC9000 ACK frames
