### ISSUE TITLE
path-specific idle timeout logic

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/multipath#210]
We introduced the idle timeout in RFC 9000 to enable endpoints to close idle connections without sending any packets (and potentially powering up the radio for that). Idle timeouts are inherently racy: the start time will vary slightly between both endpoints (by about half an RTT), and a packet sent just before expiration of the idle timeout period might be received just after the expiration.
This is ok because running into the idle timeout will completely free up all resources associated with that connection, and stray packets will elicit stateless resets, allowing the other node to do the same.

I’m not sure I fully understand how this applies to paths. It seems like there needs to be a clear signal that a path has been abandoned due to idleness. Sending this signal will be very cheap if it’s bundled with frames that would be sent anyway on a different path.

That said, I’m wondering if the idle timeout is really the right concept for paths to begin with. Peers usually apply some kind of keep-alive logic to keep a path alive, and that keep-alive period is based on the (presumed) characteristics of the path, such as the (presumed) timeouts applied by NATs, as well as the cost of sending a packet on that particular path. Would it make sense to introduce the concept of a path timeout, which could be attached to the PATH_ frames?

**Comment by mirjak** [comment]
I think there are two issues here:

One (based on the title oof the issue) is about having path-specific time-outs. This was discussed and agreed in issue #95. Or do you think there is anything additional that we need to discuss?

The second issue/proposal is to send a path_abandon frame after an idle time on another active path. I think that is a very good idea and inline with the idea to also use path_abandon after a migration event to enable the other end to remove state about the old CID. In general I think if you still have a path that is actively used it always better to be explicit. The only were you can't be explicit is if you have no actively used path, but in this case you will anyway close the whole connection about an idea-time.
