### ISSUE TITLE
editorial: section 4.3.1 talks about retransmittable frames

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/multipath#211]
This was an old term used in early QUIC draft versions, and was removed since frames are not really retransmitted. Information is retransmitted.

It should be sufficient to say that packets are declared lost. This implies that some information contained in those packets might need to be retransmitted, should the sender still wish to do so.

**Comment by mirjak** [comment]
#237 proposed to actually remove the whole sentence. I don't think it's needed.
