### ISSUE TITLE
editorial: key update requirement is hard to understand

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/multipath#213]
> [Section 19](https://rfc-editor.org/rfc/rfc9000#section-19) of [[QUIC-TRANSPORT](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#QUIC-TRANSPORT)] encodes the Connection ID Sequence Number as a variable-length integer, allowing values up to 2^62-1; in this specification, a range of less than 2^32-1 values MUST be used before updating the packet protection key.

I think I know what this is supposed to say, but I’m having trouble parsing this sentence. It would probably benefit from being reworded as a  „MUST NOT use more than 2ˆ32-1 connection IDs without a key update“, or similar.

**Comment by kazuho** [comment]
Yeah I think the entire section failed to reflect that we allow CID sequence numbers above 2^32. It goes like
> To calculate the nonce, a 96 bit path-and-packet-number is composed of the 32 bit Connection ID Sequence Number in byte order,

but what is exactly 32-bit CID sequence number?
