### ISSUE TITLE
Is ECN per path or per connection?

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/multipath#216]
I'm confused by this sentence:
> If the frame type is TBD-01, ACK_MP frames also contain the sum of QUIC packets with associated ECN marks received on the connection up to this point.

Should this be the number of packets with ECN marks received on the path, not on the connection?

If it is the number ECN marks received on the connection, how does the receiver know which path they were received on?

Example: Let's say I've received 10 new packets on path 1 and 10 new packets on path 2. Now I create an ACK_MP frame for the packets received on path 1. It doesn't make sense to me to include the ECN marks for the 10 unacknowledged packets received on path 2 in this ACK_MP frame, but that's what the text implies.

**Comment by qdeconinck** [comment]
That's indeed a typo, the ECN count should be per-path.
