### ISSUE TITLE
Path state machine needs per direction clarification for closing

### ISSUE THREAD

**Issue by gloinul** [quicwg/multipath#266]
The state machine figure for paths in Path States should have closing paths depending if the endpoint is initiating it or receiving a path_abandon. That would make the discussion much clearer.

**Comment by yfmascgy** [comment]
Are you suggestion we split the transition from "Active" to "Closing" into two branches in the figure?

**Comment by mirjak** [comment]
@gloinul ping!

**Comment by mirjak** [comment]
We removed the path states section.
