### ISSUE TITLE
When to send PATH_STATUS

### ISSUE THREAD

**Issue by kazuho** [quicwg/multipath#272]
Is an endpoint allowed to send PATH_STATUS frames for DCID=X before it observes X being used?

I think it would be natural especially for servers to bundle a NEW_CONNECTION_ID frame of DCID=X and a PATH_STATUS frame of DCID=X. That's the easiest way of declaring that all paths can be used for sending data.

However, the draft is vague if such behavior is allowed, or if it is forbidden to send PATH_STATUS frames before receiving a packet that uses that DCID value.

Hence opening the issue.

**Comment by mirjak** [comment]
I think we briefly discussed this at the last meeting and yes, I think we should allow this and yes, I think we should be more explicit in the text.
