### ISSUE TITLE
Clarify which endpoints sequence number are referenced. 

### ISSUE THREAD

**Issue by gloinul** [quicwg/multipath#310]
Section 8.1: 
"The sequence number of the Connection ID identifying the packet number space of the 0-RTT and 1-RTT packets which are acknowledged by the ACK_MP frame." 
According to the sender of this ACK. I think clarifying that the seuqence numbers are of the CIDs used belong to the receiver of the acked packets.

**Comment by mirjak** [comment]
Closing as this is obsolete with the explicit Path Id merge.
