### ISSUE TITLE
Alternative to defining a bunch of MP-specific frames

### ISSUE THREAD

**Issue by martinthomson** [quicwg/multipath#323]
With the new explicit path identifier, maybe I can suggest an improvement.

Look at Victor's https://datatracker.ietf.org/doc/draft-vvv-quic-namespaces/ It strikes me that the trick he is using with the NS frame there might be useful for MP QUIC.  Only path-specific frames would be affected.  You can even start with a default value of the current path.

**Comment by marten-seemann** [comment]
Not treating frames as separate entities breaks *a ton* of assumption I have in my code. I think this massively complicates implementations.

**Comment by qdeconinck** [comment]
Actually, this was already discussed a bit as part of #214 (https://github.com/quicwg/multipath/issues/214#issuecomment-1614669787); I believe frames should be fully self-contained, and not doing so would complicate at lot implementations.

**Comment by mirjak** [comment]
Given this was discussed in #214 already, can we close this issue?

**Comment by mirjak** [comment]
Closing this issue now. Please re-open if you think it needs further discussion.
