### ISSUE TITLE
Basic Scheduling Guidance 

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#33]
I have a sentence in the intro that this draft provide some basic scheduling guidance. I was think about something like: Data belonging to the same stream should be sent over the same path. If a new stream is opened, a packet is selected based on the current load (e.g. number of stream/max congestion window). Or something else?

Or is the plan to really not say anything here?

**Comment by mirjak** [comment]
Can we close this issue or is there any more text we want to add to this draft?

**Comment by obonaventure** [comment]
I'm writing an overview section to briefly present multipath quic that could contain this information. I'll send a PR later this week.

**Comment by mirjak** [comment]
@obonaventure I just commented on the PR. My suggestion is to move the scheduling text to a separate PR and merge it into the Packet Scheduling section that is already there later in the document, given there is now some redundancy anyway. Are you able to do that? Or should I give it a try to split up the PR?

**Comment by mirjak** [comment]
Text from Olivier from older PR:

```
The second algorithm that multipath QUIC applications will require is a packet scheduler (PS).
The PS is used when there are two or more paths that are active for a given multipath QUIC connection. In
this case, QUIC must select the path over which each frame will be sent. Many PS strategies
are possible and the best one will depend on the application's requirements. The PS should
have access to (an abstraction of) the congestion control state of each path to be able to determine
whether a path has enough capacity to carry a new packet. The PS also needs to have access to the
path's MTU as different paths do not necessarily have the same MTU. A simple PS is a round-robin
scheduler that checks the congestion window of a path before sending a QUIC packet.
Another sample PS is an algorithm that selects the path whose congestion window is open and
that has the smallest round-trip-time. This is the PS used by the Linux implementation of Multipath
TCP. Note that a multipath QUIC PS will probably treat control and data packets differently. For
example, a PS could favor low delay paths to send acknowledgments and higher bandwidth
ones for data packets. A companion draft
{{I-D.bonaventure-iccrg-schedulers}} provides several general-purpose multipath
packet schedulers. 
```

**Comment by mirjak** [comment]
@qdeconinck also mention in the cal on March 7 that we need more guidance about scheduling of ACKs

**Comment by mirjak** [comment]
I opened a new issue for the ACK guidance (#123) and am closing this one now.
