### ISSUE TITLE
How should the receiver react if it receives Connection IDs for non-authorised paths IDs?

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#336]
Closing the connection with some MP_PROTOCOL_VIOLATION error?

**Comment by michael-eriksson** [comment]
Yes.

A side note: I don't really see the point of `MP_PROTOCOL_VIOLATION`; why is RFC 9000's `PROTOCOL_VIOLATION` not good enough?

**Comment by mirjak** [comment]
This is already specified in section 7 (New Frames). PR #386 add a forward reference from section 3.5 (Allocating, Consuming, and Retiring Connection IDs).

Closing this issue as there is nothing that needs to be changed.
