### ISSUE TITLE
Clarify how new CIDs are allocated

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#338]
The process involves:

- Endpoints decide for which paths they will allocate connection identifiers, subject to both the limits imposed by "max paths" and the limits of local resource.
- Endpoint advertise connection identifiers for these paths.
- Connection identifier values must be unique for the scope of the connection, regardless of path-id.
- The number of connection-id active for a given path must not exceed the active_connection_id_limit.

It should be clear that at any given time there will be paths for which no connection ID is advertised yet, because the peer did not yet have the time or resource to advertise them. This is not an error.

**Comment by huitema** [comment]
We should perhaps make recommendations on the CID allocation strategy. Suppose for example that both endpoints advertise MAX_PATH=3, but one only provides CID for path_id=1, and the other for path_id=2. Looks obvious, but there would be no way to open either path_id=1 or path_id=2. or is there?

**Comment by mirjak** [comment]
Maybe we should specify that path IDs has to be used in-order? This is actually issue #318

**Comment by yfmascgy** [comment]
I feel the allocation strategy is more than specifying path IDs has to be used in-order. There are definitely scenarios where we would like to initiate multiple new paths concurrently but find no available CIDs for a high order path ID to use. See #370

**Comment by mirjak** [comment]
True. Assuming that endpoint usually announce a small max paths value, we could say that they should provide on CID for all paths...?

**Comment by LPardue** [comment]
Discussed during the interim: recommendations seem useful but that is the most we can do, @qdeconinck to write a PR
