### ISSUE TITLE
MAX_PATHS_BLOCKED

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/multipath#342]
In #328, we're discussing how much the path ID allocation should resemble stream ID allocation.  Along the same lines, I think the suggestion in 4.3.3 to overload MAX_PATHS to indicate that the sender would like to open more paths but is out of path IDs is not wonderful. 

> When endpoint finds it has not enough available unused Path Identifiers, it SHOULD send a MP_MAX_PATHS frame to inform the peer that it could use larger active Path Identifiers.

Following the stream ID design, there should be a MP_MAX_PATHS_BLOCKED frame for that purpose instead.

**Comment by gloinul** [comment]
This would be part of resolving #412.

**Comment by mirjak** [comment]
At IETF-120 it was agreed to add the PATHS_BLOCKED frame.
