### ISSUE TITLE
Capitalization and usage consistency

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/multipath#346]
Purely editorial nit; maybe do a global pass right before submission, but consider when updating existing text.

In RFC 9000 et al., there is a subtle distinction between capitalized and uncapitalized terms.  The "connection ID" is the value, while "Connection ID" is the field in a packet or frame.  The term "CID" never appears; DCID and SCID abbreviations are only used in examples.  This draft does not appear to follow that distinction or have a similar distinction between the "path ID" and "Path ID" fields.

(The draft is also inconsistent between "ID" and "identifier", though RFC 9000 could have been improved there as well.)

**Comment by mirjak** [comment]
Thanks! This was already mainly addressed in #334 and I now also removed CID in #352.

**Comment by mirjak** [comment]
Path ID/path identifier use still had issues. Also merged #356 now!
