### ISSUE TITLE
How is "MP_" said?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/multipath#349]
(Editorial nit.)

If it's pronounced "em pee", then references should be "an MP_whatever frame".  If it's pronounced "multipath", references should be "a MP_whatever frame".

The draft currently uses "a" throughout, which may be the answer, but I wanted to check.

**Comment by mirjak** [comment]
Thanks for checking. No idea... anybody has any glue/preferences?

I think there is actually a more generally question about naming of these frames; I will open a separate issue for that!

**Comment by mirjak** [comment]
As a quick note, if we rename to PATH_ as suggested in issue #359, this issue goes away...

**Comment by MikeBishop** [comment]
Will be resolved by #426.

**Comment by mirjak** [comment]
Yes, that is the best part of the decision to rename frames ;-)
