### ISSUE TITLE
Controlling Path and Path-ID resource

### ISSUE THREAD

**Issue by huitema** [quicwg/multipath#360]
We should say something about controlling the use of multipath resource. Something like:

Implementing the multipath extension requires expanding the use of two kind of resource: connection identifiers, which must be provided to the peer before being used in a path; and active paths contexts, which include data structures for managing the path and the associated packet number space.

The number of connection identifiers is limited by the Max Path value and by the Maximum Number of Active Connection IDs. When endpoints advertise a Max Path value, they authorize the peer to send the authorized maximum number of active connection IDs for all the newly allowed paths. The peer may advertise that many Connection IDs, and the local endpoint has to be ready to store them all.

The number of paths is limited by the Max Path value, but is also gated by the availability of connection identifiers. Endpoints advertise Max Path values that match their available resource. They only advertise Connection IDs for a specific path ID if they are ready to allocate resource for managing that path ID.

**Comment by mirjak** [comment]
@huitema can you review the proposed security considerations (see PR #383) and see if this addressed this issue already sufficiently?

**Comment by mirjak** [comment]
closing as addressed by #383
