### ISSUE TITLE
How should a client signal that it does not have enough CIDs to use for multiple unused path identifiers?

### ISSUE THREAD

**Issue by yfmascgy** [quicwg/multipath#370]
Currently, the draft states:

> To let the peer open a new path, an endpoint needs to provide its peer with connection IDs for at least one unused path identifier.

However, what if the client has an unused CID for Path ID 2 but lacks a CID for Path ID 3 and wants to concurrently open both paths 2 and 3? How should a client signal that it does not have enough CIDs to use for multiple unused path identifiers?

**Comment by mirjak** [comment]
This is already discussed in issue #338. Please comment there and close this issue!

**Comment by mirjak** [comment]
Closing. Please discuss in #338 (or reopen if that doesn't work)
