### ISSUE TITLE
What happens if requirement can't be fulfilled in MUST use new CID

### ISSUE THREAD

**Issue by gloinul** [quicwg/multipath#406]
Section 3: 
" In such a case, the receiver reacts as specified in Section 9.3 of [QUIC-TRANSPORT] by initiating path validation but MUST use a new connection ID for the same Path ID."

What happens if there are no new CID available for that path ID? Does the MUST statement come with an exception?

**Comment by mirjak** [comment]
This shouldn't happen because you always have to provide a new one when you retire an old one. However, this is not an issue at all for this draft. It's the same as in RFC9000. Therefore I'm closing this issue now. Please reopen or open a new issue if I missed anything!
