### ISSUE TITLE
Use of Respectively without a sequence

### ISSUE THREAD

**Issue by gloinul** [quicwg/multipath#410]
Section 3.3:
"Respectively, if there is still an active path, it is RECOMMENDED to send the PATH_ABANDON frames on another path."
This sentence is a bit strange, why is "respectively" used, I don't see how the recommendation are as a result of an enumerated order of any kind.

**Comment by mirjak** [comment]
I think the word "respectively" is okay here, however, this and the previous sentence are bit redundant, so I proposed to merge them in PR #420.

**Comment by gloinul** [comment]
Use of respectively when not actually enumerating appears to not match the word use. 

Independently the PR #420 looks good to solve this.
