### ISSUE TITLE
What is sending MAX_PATH_ID really doing? 

### ISSUE THREAD

**Issue by gloinul** [quicwg/multipath#412]
Section 3.5:
"Receipt of a frame with a greater Path ID is a connection error as specified in Section Section 7. When an endpoint finds it has not enough available unused path identifiers, it SHOULD send a MAX_PATH_ID frame to inform the peer that it could use new active path identifiers."

Even if it already have given the peer a higher limit? Is just repeating it having the meaning of a request, or is the sentence poorly formulated?

Also note that reference to Section 7 includes extra "section".

**Comment by mirjak** [comment]
I fixed the "section" issue in the main branch directly (in multiple places). Thanks!

However, closing this issue as duplicate. Please repeat your point in issue #342 and continue discussion there.
