### ISSUE TITLE
Can we limit the maximum value of the path ID to 2^30-1?

### ISSUE THREAD

**Issue by nandsky** [quicwg/multipath#425]
@mirjak As discussed in [#424 ]  the path ID is a variable-length integer with a maximum value of 2^32-1. This means that to store the maximum value, 8 bytes of space are required.  The encoding of 2^32-1 is 0xc0000000ffffffff.

If we limit the maximum value of the path ID to 2^30-1, then we only need 4 bytes to store it. 2^30-1 should be sufficient for the path ID, and 4 bytes also meet the requirements for nonce calculation.

https://www.rfc-editor.org/rfc/rfc9000.html#name-variable-length-integer-enc

**Comment by LPardue** [comment]
The reality is, this is going to be dealt with like every other variable length integer and handled as a u64. Then, whatever additional limits are placed on the value will come into play. 

I don't see much benefit in trying to save 4 bytes of program space per path ID by micro optimising the wire formats.

**Comment by huitema** [comment]
+1 to what @LPardue wrote. We only have a hard requirement to not use path ID larger than 2^32 -1. Yes, the encoding of the values >= 2^30 will not be very efficient. But if applications do need the extra 2 bits, encoding efficiency is not a sufficient reason to prevent them.

**Comment by mirjak** [comment]
@nandsky thanks for this proposal. This was already discussed in issue #307 and as also indicted by the answers above we concluded that this optimisation doesn't bring much benefit. Therefore I will close this issue as a duplicate.
