### ISSUE TITLE
When initial_max_path_id exceeds 2^32-1, which error code should be used?

### ISSUE THREAD

**Issue by nandsky** [quicwg/multipath#432]
If we follow the conventions of RFC 9000, should we use TRANSPORT_PARAMETER_ERROR? If so, should we explicitly document this?

[7.4. ](https://www.rfc-editor.org/rfc/rfc9000.html#section-7.4)[Transport Parameters](https://www.rfc-editor.org/rfc/rfc9000.html#name-transport-parameters)

> An endpoint MUST treat receipt of a transport parameter with an invalid value as a connection error of type TRANSPORT_PARAMETER_ERROR.

By the way, would it be more appropriate to use **TRANSPORT_PARAMETER_ERROR** instead of [**TRANSPORT_PARAMETER error**](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#section-2-11)?

> Cipher suites with a nonce shorter than 12 bytes cannot be used together with the multipath extension. If such a cipher suite is selected and the use of the multipath extension is negotiated, endpoints MUST abort the handshake with a **TRANSPORT_PARAMETER error**.

**Comment by mirjak** [comment]
Thanks for noting this oversight! Yes we need an error here and I agree that I think TRANSPORT_PARAMETER_ERROR is the right error type. I created PR #434
