### ISSUE TITLE
Should 0xffffffff be reserved for scenarios where no "max_path_id" is set?

### ISSUE THREAD

**Issue by nandsky** [quicwg/multipath#446]
In issue #425, we discussed the maximum value for max_path_id, but based on practical experience, can we retain 0xffffffff for non-multipath scenarios?

There are 4 scenarios for max_path_id negotiation:
1. Both sides have no max_path_id configured
2. Endpoint has max_path_id set, peer doesn't send it
3. Endpoint has no max_path_id set, peer sends it
4. Both sides have max_path_id set, and there's a confirmed value

as described in  [Introduction of an Explicit Path Identifier](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#name-introduction-of-an-explicit), [0, 2^32-1] have been used by multi-path，there is no value in uint32_t to represent no "max_path_id" set (initial value), so we need a uint64_t or an extra single-bit variable. for example:
```c
   uint64_t  max_path_id_remote; /* The initial value is  0xffffffffffffffff */
   uint64_t  max_path_id_local;  /* The initial value is  0xffffffffffffffff */
   uint64_t  max_path_id;  /* The initial value is  0xffffffffffffffff */
   signed    multipath_enabled:1;  /* this variable can be replaced with the expression max_path_id == 0xffffffffffffffff */
```
but:
1. If we use uint64_t, then 0x0000000100000000 - 0xffffffffffffffffff seems meaningless and waste some memory.
2. If we use a separate signed max_path_id:1 to express it, this would introduce additional complexity and also waste a little bit of memory.

If we reserve 0xffffffff for uninitialized max_path_id, then we only need three uint32_t variables to express the 4 scenarios.
```c
   uint32_t  max_path_id_remote;  /* The initial value is  0xffffffff */
   uint32_t  max_path_id_local; /* The initial value is  0xffffffff */
   uint32_t  max_path_id; /* The initial value is  0xffffffff */
```

**Comment by mirjak** [comment]
The multipath extension is indicated by the use of the initial_max_path_id transport parameter, therefore it is not possible to use the multipath extension without setting the max_path_id. The multipath_enabled transport parameter does not exist anymore and was replaced by initial_max_path_id with the introduction of the explicit path ID. If you don't want to limit the number of path IDs, you can set the initial_max_path_id transport parameter to the maximum value. See section https://quicwg.org/multipath/draft-ietf-quic-multipath.html#name-handshake-negotiation-and-t
