### ISSUE TITLE
Proposal for Integrating Deadline-Aware Streams into Multipath QUIC using DMTP

### ISSUE THREAD

**Issue by tjohn327** [quicwg/multipath#453]
### Motivation

With the rise of real-time applications such as teleoperation, live video streaming, and online gaming, there's an increasing demand for transport protocols that can efficiently handle strict latency requirements. Multipath QUIC enhances performance by utilizing multiple paths simultaneously, but it currently lacks mechanisms to guarantee data delivery within specific timeframes. Introducing deadline-aware streams to Multipath QUIC could enable applications to meet stringent latency constraints, optimizing for low-latency and high-reliability scenarios.
Additionally, the ability to have multiple paths using the same 4-tuple opens up the possibility of leveraging paths from path-aware networks like SCION, source routing, and others. This expands the pool of available paths beyond traditional IPv4 and IPv6 routes, potentially increasing the effectiveness of deadline-aware mechanisms like those proposed in DMTP.

#### Relevant Discussion

In a recent discussion around the Multipath Extension for QUIC ([Issue #378](https://github.com/quicwg/multipath/issues/378)), the use of multiple paths with the same 4-tuple found support. This aligns with the idea of integrating paths from path-aware networks, enabling Multipath QUIC to utilize all available paths provided by the system.

### How DMTP Fits In

The Deadline-aware Multipath Transport Protocol (DMTP) is tailored for deadline-sensitive communication over multiple paths. It employs strategies like smart retransmissions and Forward Error Correction (FEC) to optimize packet delivery based on latency deadlines, ensuring retransmissions occur only when they are likely to meet these deadlines. These methods align well with Multipath QUIC's capabilities, potentially allowing for efficient and reliable deadline-aware data transmission across different network paths.

### Key Concepts of DMTP

- Path Optimization: DMTP dynamically selects paths based on metrics like latency, bandwidth, and packet loss. This approach complements Multipath QUIC's ability to manage multiple paths effectively.
- Adaptive FEC: By integrating FEC, DMTP reduces the need for retransmissions, proactively adding redundancy when random losses are detected. This could enhance Multipath QUIC's congestion control mechanisms.
- Smart Retransmissions: DMTP only retransmits packets if they are predicted to meet the deadline, which helps to avoid unnecessary retransmissions. Incorporating this into QUIC's scheduling could improve overall efficiency.

For more detailed information on DMTP, please refer to our [paper](https://doi.org/10.23919/IFIPNetworking57963.2023.10186417).
We have developed a prototype implementation of DMTP, which we plan to open-source in the near future.

### How to get it integrated into Multipath QUIC

To integrate DMTP into Multipath QUIC, we propose implementing DMTP's mechanisms as a custom scheduler and congestion controller within the Multipath QUIC framework. Additionally, we suggest introducing a new transport parameter to signal support for deadline-aware streams during the handshake. For incorporating deadline information into data transmission, our proposal is to define an additional extension frame type called DEADLINE_CONTROL. The aim of this frame is to signal deadline-awareness for specific streams and indicate their associated deadlines.

### Request for Feedback

We're considering integrating deadline-aware streaming concepts from DMTP into Multipath QUIC and are interested in the community's perspective. Do you see value in this exploration? Are there potential challenges or compatibility concerns we should be aware of? Your feedback will be instrumental in guiding this proposal.

**Comment by LPardue** [comment]
Hi @tjohn327 

Thanks for bringing your ideas here with a clear writeup.

However, this repository is for tracking issues and proposals for the text that is in scope of the Multipath QUIC extension itself.  

There will be many exciting opportunities and areas of research or innovation on top the completed multipath work. It sounds like you have an additional extension on top of that. The best venue to solicit interest or comments on that is on the QUIC mailing list. So I'd ask you to start a new thread there with your opening comment.

If there are specific issues or ideas you have on the multipath extension itself, that can ensure it is a good foundation for other ideas please do open specific issues or PRs (or contribute to existing ones). However, I want to be clear that we are now at the stage if the draft process where there is high bar for consensus on and new or major design changes.

**Comment by tjohn327** [comment]
Thank you very much for your feedback and guidance @LPardue .

I understand that the Multipath QUIC draft is in its final stages, and I appreciate your suggestion to initiate a discussion on the QUIC mailing list.

I have prepared a [diff](https://github.com/quicwg/multipath/compare/main...tjohn327:multipath:deadline-aware-streams) with changes to incorporate deadline-aware streams into Multipath QUIC. While I recognize this may not fit within the immediate scope of the current draft, I thought it might be helpful to share this proposal here to gather initial impressions. I'm prepared to start a new thread on the QUIC mailing list to discuss this extension in detail with the broader community.

If time permits, I would greatly appreciate any initial thoughts on the diff or suggestions on how best to proceed. I'm eager to contribute positively and align with the group's direction.

Thank you again for your time and consideration.

**Comment by LPardue** [comment]
Closing this as there is now a mailing list thread.
