### ISSUE TITLE
Rename PATHS_BLOCKED to PATH_BLOCKED

### ISSUE THREAD

**Issue by gloinul** [quicwg/multipath#472]
Currently all the other multipath frame types are PATH_ except PATHS_BLOCKED. And really the description for PATHS_BLOCKED really just indicates that one path was blocked from being established. There might be more, but we anyway don't have any field in the frame to indicate how many paths the endpoint would like to establish. So I propose that we rename it PATH_BLOCKED for consistency reason.

**Comment by mirjak** [comment]
We actually just renamed it to PATHS_BLOCKED right before the merge to align with STREAMS_BLOCKED in RFC9000. But thanks for checking. I'll close the issue as this was already previously discussed.
