### ISSUE TITLE
ECN support and single/multiple packet number spaces

### ISSUE THREAD

**Issue by obonaventure** [quicwg/multipath#87]
With a packet number space per path, the ACK_MP frame provides the per path ECN feedback that enables a sender to detect congestion using ECN on a specific path. The per-path congestion control can adjust the congestion window based on the received feedback.

With a single packet number space shared among the different paths, the ECN fields of the ACK frame provide ECN information that is common to all paths. This makes it impossible for a sender to determine which path is affected by congestion when it receives an ACK frame with positive ECN counters. A per-path congestion control cannot easily react to such an ambiguous ECN feedback.

**Comment by mirjak** [comment]
This is a very point and should also be consider in the discussion on one vs. multiple PNSs. I will try to make a text proposal for the draft to explain the problem. I think for the single number space approach this means that you cannot use ECN or you need to specify a new ECN ACK frame. I guess that could be a separate draft or in this draft but maybe we just leave this open for now as long as we didn't decide for one or the other approach.

**Comment by mirjak** [comment]
Briefly discussed at IETF-113. One comment that we should support ECN.

**Comment by mirjak** [comment]
ECN text is included in PR #103 now.

**Comment by mirjak** [comment]
#103 was merged.
