### ISSUE TITLE
Do we need a transport parameter to negotiate max path idle timeout?

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#95]
This was discussed in issue #51 and PR #94.

**Comment by yfmascgy** [comment]
Regarding the max_idle_timeout, RFC9000 says "To avoid excessively small idle timeout periods, endpoints MUST increase the idle timeout period to be at least three times the current Probe Timeout (PTO)." As in multi-path QUIC, the PTO is per-path, when max_idle_timeout is used to close a connection, it makes sense to set max_idle_timeout = 3*max(PTO_1, PTO_2). But when it comes to close a path, I am not sure if the timeout for path1 should also depend on the PTO of path 2?

**Comment by qdeconinck** [comment]
I think there are two idle timeouts: the "connection idle timeout" and the "path idle timeout".

For the "connection idle timeout", I agree that it should be at least 3*PTO_max. Triggering this timeout closes the connection.

For the "path idle timeout", this might be a way to have a stronger guarantee to stop using paths (closing them) after some inactivity than the text proposed in #94. Still, if we define such a mechanism, we need to know whether all paths should have the same path timeout value or not (in the latter case, a transport parameter might not be the best way).

**Comment by obonaventure** [comment]
I would avoid having a different timer for a path than for a connection. That would make the protocol more complex without a lot of benefits. If a host wants to use a shorter timeout per path than the connection timeout, it can simply define it and use a PATH_ABANDON frame to indicate that the path is abandoned. 

However, we need to be clearer in 3.2.3 to indicate that a path can be considered valid if either packets are received on that path or packets sent on that path are acknowledged (possibly on another path)

**Comment by mirjak** [comment]
Presented at IETF-113 but no time for discussion.

**Comment by yfmascgy** [comment]
I have submitted PR#124 to resolve this issue according to the above discussion.

**Comment by mirjak** [comment]
PR was merged but forgot to close issue...
